sudo: required

language: java

services:
  - docker

jobs:
  include:
  - stage: Build and Test on CouchDB 1.x
    language: java
    install:
      - docker pull couchdb:1.7.1
      - docker run -d -p 127.0.0.1:5984:5984 -e COUCHDB_USER=couchdb -e COUCHDB_PASSWORD=couchdb couchdb:1.7.1
      - sed 's/^couchdb.username.*/couchdb.username=couchdb/;s/^couchdb.password.*/couchdb.password=couchdb/' -i src/test/resources/couchdb.properties
  - stage: Build and Test on CouchDB 2.x
    language: java
    install:
      - docker pull couchdb:2.1.1
      - docker run -d -p 127.0.0.1:5984:5984 -e COUCHDB_USER=couchdb -e COUCHDB_PASSWORD=couchdb couchdb:2.1.1
      - sed 's/^couchdb.username.*/couchdb.username=couchdb/;s/^couchdb.password.*/couchdb.password=couchdb/' -i src/test/resources/couchdb.properties
