# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  set-couchdb-credentials:
    parameters:
      username:
        default: "couchdb"
        type: string
      password:
        default: "couchdb"
        type: string
    steps:
      - run:
         name: Config CouchDB credentials for testing
         command: |
            sed 's/^couchdb.username.*/couchdb.username=<<parameters.username>>/;s/^couchdb.password.*/couchdb.password=<<parameters.password>>/' -i src/test/resources/couchdb.properties
            sed 's/^couchdb.username.*/couchdb.username=<<parameters.username>>/;s/^couchdb.password.*/couchdb.password=<<parameters.password>>/' -i src/test/resources/couchdb-2.properties
  create-system-dbs:
    parameters:
      username:
        default: "couchdb"
        type: string
      password:
        default: "couchdb"
        type: string
    steps:
      - run:
         name: Prepare CouchDB
         command: |
            curl -X PUT http://127.0.0.1:5984/_users -u <<parameters.username>>:<<parameters.password>>
            curl -X PUT http://127.0.0.1:5984/_replicator -u <<parameters.username>>:<<parameters.password>>
            curl -X PUT http://127.0.0.1:5984/_global_changes -u <<parameters.username>>:<<parameters.password>>
  maven-build:
    steps:
     - run:
          name: Build
          command: mvn -B -DskipTests clean package
  maven-test:
    steps:
     - run:
          name: Test
          command: mvn test
executors:
  couchdb:
    parameters:
      version:
        description: "couchdb version tag"
        default: "3.3.1"
        type: string
    docker:
      - image: cimg/openjdk:11.0
      - image: couchdb:<<parameters.version>>
        environment:
          COUCHDB_USER: couchdb
          COUCHDB_PASSWORD: couchdb
jobs:
  test-couchdb:
    parameters:
      version:
        description: "version tag"
        default: "3.2.0"
        type: string
    executor:
      name: couchdb
      version: <<parameters.version>>    
    steps:
      - checkout
      - maven-build
      - set-couchdb-credentials
      - when:
          condition: 
            not:
              equal: ["1.7.2",<<parameters.version>>]
          steps:
            - create-system-dbs
      - when:
          condition: 
            equal: ["3.3.1",<<parameters.version>>]
          steps:
            - run:
               name: Test-and-Sonar
               command: mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -Dsonar.projectKey=es.indaba:lightcouch -Dsonar.organization=indaba -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
      - unless:
          condition: 
              equal: ["3.3.1",<<parameters.version>>]
          steps:
           - maven-test

workflows:
  build-and-test: 
    jobs:
      - test-couchdb:
         matrix:
            parameters:
              version:
                - 3.3.1
                - 2.3.1
                - 1.7.2
